### ISSUE TITLE
Want to know what I did? 

### ISSUE THREAD

**Issue by Zarcolio** [x0xr00t/sl0ppy-customdecode#1]
https://chat.openai.com/share/a5d2084e-1493-4103-b4fc-84d4c5a0014d 😉

**Comment by x0xr00t** [comment]
@Zarcolio That is a method u could use indeed, pretty nifty to be honest. Sadly it not fully matches the alphabet as far as i can see, sum of the chars should be swapped around likely, mine code to encode is mainly done in python, working on the decoder part as we speak, maybe i release the source to the custom encoder decoder sooner or later.
